version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-tasks-app
    ports:
      - '5000:5000'
    environment:
      STAGE: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: amir
      DB_PASSWORD: 0251
      DB_DATABASE: task-management
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: nest-tasks-db
    environment:
      POSTGRES_USER: amir
      POSTGRES_PASSWORD: 0251
      POSTGRES_DB: task-management
    ports:
      - '5334:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
